# Generated by Django 5.2.15 on 2026-06-16 14:01

from django.db import migrations


def add_price(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')

    for product in OrderProduct.objects.all().iterator():
        product.price = product.product.price * product.quantity
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20260616_1637'),
    ]

    operations = [
        migrations.RunPython(add_price),
    ]
