# Generated by Django 5.2.15 on 2026-06-16 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20260616_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость'),
            preserve_default=False,
        ),
    ]
