# Generated by Django 5.2.15 on 2026-06-16 14:09

from django.db import migrations


def add_cost(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')

    for product in OrderProduct.objects.all().iterator():
        product.cost = product.price
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_orderproduct_cost'),
    ]

    operations = [
        migrations.RunPython(add_cost),
    ]
