# Generated by Django 5.2.15 on 2026-06-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_remove_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('cook', 'В сборке'), ('delivery', 'В пути'), ('done', 'Доставлен')], db_index=True, default='new', max_length=20),
        ),
    ]
