# Generated by Django 5.2.15 on 2026-06-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_called_at_order_created_at_order_delivery_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='called_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_at',
        ),
    ]
