# Generated by Django 5.2.15 on 2026-06-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('online', 'Онлайн'), ('cash', 'наличными')], db_index=True, default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('cook', 'В сборке'), ('delivery', 'В пути'), ('done', 'Доставлен')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
