# Generated by Django 5.2.15 on 2026-06-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('anew', 'Необработанный'), ('bcook', 'В сборке'), ('cdelivery', 'В пути'), ('done', 'Доставлен')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
