# Generated by Django 5.2.15 on 2026-06-18 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Звонок покупателю'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Заказ создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Передан в доставку'),
        ),
    ]
