# Generated by Django 5.2.15 on 2026-06-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_called_at_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('online', 'Онлайн'), ('cash', 'наличными')], db_index=True, max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
