# Generated by Django 5.2.15 on 2026-06-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='Location',
        ),
    ]
