# Generated by Django 5.2.15 on 2026-06-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_classname_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'адрес', 'verbose_name_plural': 'адреса'},
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=200, unique=True, verbose_name='адрес'),
        ),
    ]
